// eslint-disable-next-line import/no-anonymous-default-export
module.exports = {
  extends: ["@commitlint/config-conventional"],
  defaultIgnores: true,
  helpUrl: "https://github.com/conventional-changelog/commitlint/#what-is-commitlint",
  rules: {
    "body-leading-blank": [1, "always"],
    "body-max-line-length": [2, "always", 240],
    "footer-leading-blank": [1, "always"],
    "footer-max-line-length": [2, "always", 200],
    "header-max-length": [2, "always", 150],
    "scope-case": [2, "always", "lower-case"],
    "subject-empty": [2, "never"],
    "subject-full-stop": [2, "never", "."],
    "type-empty": [2, "never"],
    "type-enum": [
      2,
      "always",
      [
        "build",
        "core",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
        "translation",
        "security",
        "changeset",
        "install",
        "api",
        "cleanup",
        "setup",
      ],
    ],
  },
};
